### ISSUE TITLE
[Bug] Fix lint action, update Ameba or pin to Crystal 1.20.3

### ISSUE THREAD

**Issue by Fijxu** [omarroth/invidious#5857]
The current ameba version we use on our shards.yml doesn't seem to build with the latest Crystal version (1.21.0), therefore we will need to update Ameba or pin Crystal to 1.20.3 to make the lint action work again.

We could take some changes from https://github.com/iv-org/invidious/pull/5589

Logs from the lint action: 

```
I: Building: ameba
E: Error target ameba failed to compile:
The 'preview_mt' flag is deprecated. Resize the default execution context, or start additional contexts instead.

A total of 1 warnings were found.
Showing last frame. Use --error-trace for full trace.

In src/ameba/tokenizer.cr:88:15

 88 | lexer.next_string_array_token
            ^----------------------
Error: Error: undefined method 'next_string_array_token' for Crystal::Lexer (compile-time type is Crystal::Lexer+)
Error: Process completed with exit code 1.
```

**Comment by unixfox** [comment]
> We could take some changes from [#5589](https://github.com/iv-org/invidious/pull/5589)

👍

**Comment by Fijxu** [comment]
https://github.com/crystal-ameba/ameba/issues/756

For now we will pin crystal to 1.20.3 and I'll keep this issue open until Ameba is fixed.

**Comment by unixfox** [comment]
Good for me. I guess it would be awesome if @SamantazFox comes around for updating the code to the latest Ameba because they really know well the invidious code.

**Comment by Sija** [comment]
> https://github.com/crystal-ameba/ameba/issues/756
> 
> For now we will pin crystal to 1.20.3 and I'll keep this issue open until Ameba is fixed.

Ameba is compatible since some time already, you just need to update it.

**Comment by Fijxu** [comment]
> > [crystal-ameba/ameba#756](https://github.com/crystal-ameba/ameba/issues/756)
> > For now we will pin crystal to 1.20.3 and I'll keep this issue open until Ameba is fixed.
> 
> Ameba is compatible since some time already, you just need to update it.

We prefer to use stable releases and 1.7.0 seems to be on preview still, and the latest stable, ameba 1.6.4 doesn't build with Crystal 1.21.0 ^^'
https://github.com/crystal-ameba/ameba/issues/756#issuecomment-5153553498
